# Generated by Django 4.2.3 on 2023-07-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_careerassesmentquestion_careerassesmentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerassessment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.careerassesmentanswer'),
        ),
        migrations.AlterField(
            model_name='careerassessment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.careerassesmentquestion'),
        ),
    ]
