# Generated by Django 4.2.3 on 2023-08-24 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0005_careerassessmentresponse_userchat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSuggesstionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_ai', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='careersuggestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='IndustryInsight',
        ),
        migrations.RemoveField(
            model_name='interviewtip',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='CareerSuggestion',
        ),
        migrations.DeleteModel(
            name='InterviewTip',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='UserChat',
        ),
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
